Clean up and refactor code
Irrational-Encoding-Wizardry/vs-encode pull request #1
Opened 2022-06-19 19:11 UTC by Setsugennoao

2022-06-19 21:39 UTC, LightArrowsEXE requested changes
Thanks! This helps a lot. Got a couple comments, though:

2022-06-19 21:39 UTC, LightArrowsEXE commented on vsencode/audio.py
>          track_channels = [2] * len(audio_files)
Do you think you could maybe figure out a way to reliably get all the channels per track? Right now it just assumes 2.0 for every track, as you can see here.

2022-06-19 21:39 UTC, LightArrowsEXE commented on vsencode/audio.py
> +                language.UNDEFINED, i, *xml_arg
It still passes `language.UNDEFINED` here rather than the new languages. Add that to the zip ig?

2022-06-19 21:39 UTC, LightArrowsEXE commented on vsencode/audio.py
> +        # try:
Since we're properly using the extractor now, can't we just remove this commented bit?

2022-06-19 21:39 UTC, LightArrowsEXE commented on vsencode/encoder.py
> +            self.v_lang, self.a_lang, self.c_lang = lang[0], lang[1:-1], lang[-1]
Right now we're no longer handling the case where users give a proper list of languages (1 video, 1 audio, and 1 chapters list). Also wondering whether it wouldn't make sends to set it to video=0, audio=1, chapters=0 if the user only passes two items?

2022-06-19 21:39 UTC, LightArrowsEXE commented on vsencode/encoder.py
> +        )
This was just for testing. We can announce this info per method instead.

2022-06-19 21:39 UTC, LightArrowsEXE commented on vsencode/encoder.py
>          logger.info(f"Creating an intermediary lossless encode using {encoder}.")
Maybe worth adding a type check here to see if what is returned is a function, if possible. I assume not, but hey, maybe?

2022-06-19 21:39 UTC, LightArrowsEXE commented on vsencode/encoder.py
> +        ]
This should be done first. I want the custom trims to be relative to the original trims. So if the original trim was (24, -24) and the custom trim is (24, -24) again, the end result should be (48, -48).

2022-06-19 21:39 UTC, LightArrowsEXE commented on vsencode/encoder.py
> +            vencoder: Type[AudioEncoder]
aencoder

2022-06-19 21:51 UTC, LightArrowsEXE commented
I'd also like for all the chainable methods in the EncodeRunner class right now to become inherited classes instead. This should make the code a lot easier to divvy up into sections without having a massive basically-monolithic and glorified `__main__`. I'd like these to be put into their own directory as well and imported that way. Maybe call it "chains" or something, idk.

2022-06-20 10:22 UTC, Setsugennoao commented on vsencode/encoder.py
> +            self.v_lang, self.a_lang, self.c_lang = lang[0], lang[1:-1], lang[-1]
Not true, case is still handled and the code was wrong before (self.a_lang was List\[List\[int]])
Will fall back to self.v_lang for c_lang

2022-06-20 10:33 UTC, Setsugennoao commented on vsencode/audio.py
>          track_channels = [2] * len(audio_files)
I think it's out of the scope of this PR, will open an issue

2022-08-07 02:44 UTC, LightArrowsEXE commented
Will this see more movement again soon?

2022-08-27 23:16 UTC, merged